### ISSUE TITLE
Error when import cpylmnl

### ISSUE THREAD

**Issue by uttu90** [chamaken/cpylmnfct#1]
Dear Mr.charmaken,
I have already clone your source code and installed it successfully. However, when I run the code (import cpylmnl) an error has occurred:

> > > import cpylmnl
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "build/bdist.linux-x86_64/egg/cpylmnl/**init**.py", line 55, in <module>
> > >   File "build/bdist.linux-x86_64/egg/cpylmnl/_libmnlh.py", line 4, in <module>
> > >   File "build/bdist.linux-x86_64/egg/cpylmnl/_cproto.py", line 9, in <module>
> > >   File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in **init**
> > >     self._handle = _dlopen(self._name, mode)
> > > OSError: libmnl.so: cannot open shared object file: No such file or directory

Could you please tell me how can I handle it?
Thanks,

**Comment by chamaken** [comment]
you need to install libmnl C libraty
since this is not a pure puthon implementation

**Comment by uttu90** [comment]
Dear Mr.charmaken,
How can I install it? I already have libnetfilter_conntrack installed

**Comment by chamaken** [comment]
can you find libmnl by ldconfig -v ?

**Comment by uttu90** [comment]
Dear Mr.charmaken,
I use ubuntu server 14.04
I run ldconfig-v | grep libmnl, I had the result: libmnl.so.0 -> libmnl.so.0.1.0.

**Comment by chamaken** [comment]
you may need to install libmnl-dev package.

**Comment by uttu90** [comment]
Hi,
I already fixed this by installing lbmnl-dev as you suggested. However, I receive another error when trying to run code:
 In [6]: import cpylmnl
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-cee1653d8603> in <module>()
----> 1 import cpylmnl

/home/stack/Downloads/uttu/python-conntrack/build/bdist.linux-x86_64/egg/cpylmnl/__init__.py in <module>()

/home/stack/Downloads/uttu/python-conntrack/build/bdist.linux-x86_64/egg/cpylmnl/_libmnlh.py in <module>()

/home/stack/Downloads/uttu/python-conntrack/build/bdist.linux-x86_64/egg/cpylmnl/_cproto.py in <module>()

/usr/lib/python2.7/ctypes/__init__.pyc in __getattr__(self, name)
    376         if name.startswith('__') and name.endswith('__'):
    377             raise AttributeError(name)
--> 378         func = self.__getitem__(name)
    379         setattr(self, name, func)
    380         return func

/usr/lib/python2.7/ctypes/__init__.pyc in __getitem__(self, name_or_ordinal)
    381 
    382     def __getitem__(self, name_or_ordinal):
--> 383         func = self._FuncPtr((name_or_ordinal, self))
    384         if not isinstance(name_or_ordinal, (int, long)):
    385             func.__name__ = name_or_ordinal

AttributeError: /usr/lib/x86_64-linux-gnu/libmnl.so.0: undefined symbol: mnl_socket_open2

**Comment by chamaken** [comment]
Hi,
could you try on current cpylmnl?
I ve tried to fix "undefined symbol: mnl_socket_open2"

**Comment by uttu90** [comment]
I can import it. Thanks for your great support.
But when I run the example, another error is raised:

sudo python nfct-mnl-dump.py 
Traceback (most recent call last):
  File "nfct-mnl-dump.py", line 12, in <module>
    import cpylmnfct as nfct
  File "build/bdist.linux-x86_64/egg/cpylmnfct/__init__.py", line 54, in <module>
  File "build/bdist.linux-x86_64/egg/cpylmnfct/_conntrack.py", line 8, in <module>
  File "build/bdist.linux-x86_64/egg/cpylmnfct/_cproto.py", line 92, in <module>
  File "/usr/lib/python2.7/ctypes/__init__.py", line 378, in __getattr__
    func = self.__getitem__(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 383, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: /usr/lib/x86_64-linux-gnu/libnetfilter_conntrack.so: undefined symbol: nfct_bitmask_clear

Can you show me how to fix it? Thank you very much

**Comment by chamaken** [comment]
could you try on current cpylmnfct?
I tried to fix unresolved symbols.

**Comment by uttu90** [comment]
Hi,
I have tested and It run very well. Would you like to public your project to pip? Thanks for your effort.
