### ISSUE TITLE
Delete icmp entry

### ISSUE THREAD

**Issue by uttu90** [chamaken/cpylmnfct#2]
I have another question related to delete icmp entry:
- How we can delete the icmp entry while it do not have sport and dport?
- I try to update only src_address and dst_address, but it is failed
- If we have to assign icmp_code and icmp_type. How can we do it?

**Comment by chamaken** [comment]
First of all, you can get better answers from netfilter-users ML
when asking such a question.

Assume you wrote about conntrack entry.
You may get ICMP entry by specifying ATTR_ICMP_TYPE and ATTR_ICMP_CODE,
but you can not update src and dst address.

I think it's goot to see conntrack tool source, nl_update_conntrack()::netlink.c
and kernel source ctnetlink_new_conntrack()::net/netfilter/nf_conntrack_netlink.c.
The callchain in kernel side is ctnetlink_new_conntrack(), ctnetlink_change_conntrack()
if no NLM_F_EXCL (which means update), ctnetlink_change_protoinfo() and
L4 dependent from_nlattr(). Try to grep from_nlattr in that kernel directory,
and see what's going on protocol dependent functions.

**Comment by uttu90** [comment]
Actually, I have already summit this question to the ML, but got no answer yet. I also see something on there: https://github.com/svinota/pyroute2/tree/master/pyroute2/netlink/nfnetlink. Do you think we can create a Python library for Netlink from this?

**Comment by chamaken** [comment]
I have created a [ICMP echo examples](https://github.com/chamaken/cpylmnfct/tree/icmp-examples) and hope it shall help your issue.
And I realize `int(ipaddr.IPv4Address)` to be changed to network byteorder ;-)

**Comment by uttu90** [comment]
I can apply it, very helpful. Thank you so much!
